Python=3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:11:29) [Clang 20.1.8 ]
Pytest=8.4.2
Timestamp=2026-06-28 20:41:19
DeviceID=TC55LJMR59W8ZPRK
App=com.cloudedge.smarteye
DeviceSN=129653415
